var Boss=function(a){this.boss=new window[bosses[a]];this.hit=this.boss.hit;this.tick=function(){this.boss.tick()}};
var bosses=["Boss1","null"];
this.ndgmr=this.ndgmr||{};
(function(){var p=document.createElement("canvas"),t=p.getContext("2d");t.save();var q=document.createElement("canvas"),u=q.getContext("2d");u.save();var s=[],w=function(a,b){var d,e;d=j(a);e=j(b);return v(d,e)};ndgmr.checkRectCollision=w;ndgmr.checkPixelCollision=function(a,b,d,e){if(ndgmr.DEBUG||ndgmr.DEBUG_COLLISION)document.body.appendChild(p),document.body.appendChild(q);e=e||!1;var c,g;c=a instanceof createjs.Bitmap?{width:a.image.width,height:a.image.height}:a.spriteSheet.getFrame(a.currentFrame).rect;g=
b instanceof createjs.Bitmap?{width:b.image.width,height:b.image.height}:b.spriteSheet.getFrame(b.currentFrame).rect;if(!(Math.abs(b.x-a.x)<g.width*b.scaleX+c.width*a.scaleX&&Math.abs(b.y-a.y)<g.height*b.scaleY+c.height*b.scaleY))return!1;c=w(a,b);if(!c)return!1;d=Math.min(0.99999,d||0);p.width=c.width;p.height=c.height;q.width=c.width;q.height=c.height;a=x(c,a,t);a:{b=x(c,b,u);g=c.width;var j=c.height,m,n,h,k,l=3,f={x:Infinity,y:Infinity,x2:-Infinity,y2:-Infinity};for(k=0;k<j;++k)for(h=0;h<g;++h){m=
a.length>l+1?a[l]/255:0;n=b.length>l+1?b[l]/255:0;if(m>d&&n>d)if(e)h<f.x&&(f.x=h),h>f.x2&&(f.x2=h),k<f.y&&(f.y=k),k>f.y2&&(f.y2=k);else{a={x:h,y:k,width:1,height:1};break a}l+=4}Infinity!=f.x?(f.width=f.x2-f.x+1,f.height=f.y2-f.y+1,a=f):a=null}if(a)a.x+=c.x,a.x2+=c.x,a.y+=c.y,a.y2+=c.y;else return!1;return a};var x=function(a,b,d){var e,c;b instanceof createjs.Bitmap?c=b.image:b instanceof createjs.BitmapAnimation&&(e=b.currentFrame+b.spriteSheet.getFrame(b.currentFrame).image.src,s[e]?c=s[e]:s[e]=
c=createjs.SpriteSheetUtils.extractFrame(b.spriteSheet,b.currentFrame));e=b.globalToLocal(a.x,a.y);d.restore();d.clearRect(0,0,a.width,a.height);d.rotate(r(b,"rotation")*(Math.PI/180));d.scale(r(b,"scaleX","*"),r(b,"scaleY","*"));d.translate(-e.x,-e.y);d.drawImage(c,0,0,c.width,c.height);return d.getImageData(0,0,a.width,a.height).data},r=function(a,b,d){d=d||"+";if(a.parent&&a.parent[b]){var e=a[b];a=r(a.parent,b,d);return"*"==d?e*a:e+a}return a[b]},v=function(a,b){var d,e,c,g,j,m,n,h;d=a.x+(c=a.width/
2);e=a.y+(g=a.height/2);j=b.x+(m=b.width/2);n=b.y+(h=b.height/2);d=Math.abs(d-j)-(c+m);e=Math.abs(e-n)-(g+h);return 0>d&&0>e?(d=Math.min(Math.min(a.width,b.width),-d),e=Math.min(Math.min(a.height,b.height),-e),{x:Math.max(a.x,b.x),y:Math.max(a.y,b.y),width:d,height:e}):null};ndgmr.calculateIntersection=v;var j=function(a){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){var d=a.children,e=d.length,c;for(a=0;a<e;a++)c=j(d[a]),c.x<b.x&&(b.x=c.x),c.y<b.y&&(b.y=c.y),
c.width>b.width&&(b.width=c.width),c.height>b.height&&(b.height=c.height)}else{var g;if(a instanceof createjs.Bitmap)g=a.image;else if(a instanceof createjs.BitmapAnimation)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image)g=a.spriteSheet.getFrame(a.currentFrame).rect;else return b;else return b;d=a.localToGlobal(0,0);e=a.localToGlobal(g.width,g.height);c=a.localToGlobal(g.width,0);a=a.localToGlobal(0,g.height);b.x=Math.min(Math.min(Math.min(d.x,
e.x),c.x),a.x);b.y=Math.min(Math.min(Math.min(d.y,e.y),c.y),a.y);b.width=Math.max(Math.max(Math.max(d.x,e.x),c.x),a.x)-b.x;b.height=Math.max(Math.max(Math.max(d.y,e.y),c.y),a.y)-b.y}return b};ndgmr.getBounds=j})();
window.Boss1=function(){this.obj=new Bitmap("./sprites/enemies/bosses/boss1.png");this.obj.state=2;this.obj.speed=10;this.obj.x=640;this.obj.y=240;this.obj.vx=-50;this.obj.vy=0;this.obj.hp=200;this.obj.worth=500;this.obj.weapon1=new Weapon("SINGLELINEAR");this.obj.weapon2=new Weapon("SINGLEDIRECTIONAL");this.obj.dead=!1;var a=this;this.obj.hit=function(){a.obj.hp--;0>=a.obj.hp&&(a.obj.dead=!0,new Explosion(a.obj.x-20,a.obj.y),new Explosion(a.obj.x,a.obj.y-20),new Explosion(a.obj.x+20,a.obj.y+20),
a.obj.state=3,game.score+=a.obj.worth,game.level.score+=a.obj.worth,game.updateScore(),game.bossesContainer.removeChild(a.obj),game.level.state="COMPLETE")};this.tick=function(){if(a.obj.dead)return!1;switch(a.obj.state){case 0:a.obj.x+=33*a.obj.vx/1E3;a.obj.y+=33*a.obj.vy/1E3;break;case 1:a.obj.vx=50*Math.cos(0.05*a.obj.speed);a.obj.speed++;a.obj.x+=33*a.obj.vx/1E3;a.obj.y+=33*a.obj.vy/1E3;a.obj.y+a.obj.image.height>game.canvas.height&&(a.obj.y=game.canvas.height-a.obj.image.height,a.obj.vy*=-1);
0>a.obj.y&&(a.obj.y=0,a.obj.vy*=-1);a.obj.weapon1.shoot(this.obj,null,a.obj.y-a.obj.regY+20);a.obj.weapon2.shoot(this.obj);break;case 2:0<a.obj.hp&&setTimeout(function(){a.obj.state=0},3E3)}0==a.obj.state&&450>=a.obj.x&&(a.obj.vx=0,a.obj.vy=80,a.obj.state=1)}};
var OrbEnemy=function(){this.sprite="orb.png";this.height=this.width=25;this.bullet="enemyBullet.png";this.fire=!0;this.speed=15;this.hp=1;this.worth=100;this.givePowerup=!1;this.powerupImage=null;this.isRotating=!0;this.weapon="SINGLELINEAR"};
var Orb2Enemy=function(){this.sprite="orb2.png";this.height=this.width=25;this.bullet="enemyBullet.png";this.fire=!0;this.speed=15;this.hp=1;this.worth=100;this.givePowerup=!0;this.powerupImage=null;this.isRotating=!0;this.weapon="SINGLEDIRECTIONAL"};
var Enemy=function(d){this.obj={};var a=this;this.data=d;this.init=function(a){switch(this.data.enemyClass){case "orb":var b=new OrbEnemy;break;case "orb2":b=new Orb2Enemy}this.obj=new Bitmap("./sprites/enemies/"+b.sprite);this.obj.x=a.x;this.obj.y=a.y;this.obj.init=a.init;this.obj.regX=b.width/2;this.obj.regY=b.height/2;this.obj.bullet=b.bullet;this.obj.scaleX=1;this.obj.scaleY=1;this.obj.firer=b.fire;this.obj.speed=a.speed;this.obj.hp=b.hp;this.obj.givePowerup=b.givePowerup;this.obj.powerupImage=
b.powerupImage;this.obj.worth=b.worth;this.obj.rtData=a;this.obj.tick=this.tick;this.obj.hit=this.hit;this.obj.kill=this.kill;this.obj.fire=this.fire;this.obj.isRotating=b.isRotating;this.obj.state=0;this.obj.angle=a.startAngle;this.weapon=new Weapon(b.weapon)};this.tick=function(){switch(a.obj.rtData.trajectory){case "ROTATION":if(0==a.obj.state){var c=a.obj.x-a.obj.rtData.x,b=a.obj.y-a.obj.rtData.y,c=Math.sqrt(c*c+b*b);0>=a.obj.rtData.distance-c&&(a.obj.state=1)}1==a.obj.state&&(a.obj.angle+=a.obj.rtData.rotateSpeed);
1==a.obj.state&&Math.abs(a.obj.angle-a.obj.rtData.startAngle)>=a.obj.rtData.angleToRotate&&(a.obj.angle=0>a.obj.rtData.rotateSpeed?a.obj.angle+(Math.abs(a.obj.angle-a.obj.rtData.startAngle)-a.obj.rtData.angleToRotate):a.obj.angle-(Math.abs(a.obj.angle-a.obj.rtData.startAngle)-a.obj.rtData.angleToRotate),a.obj.state=2);a.obj.vx=Math.cos(a.obj.angle)*a.obj.speed;a.obj.vy=Math.sin(a.obj.angle)*a.obj.speed;a.obj.x+=33*a.obj.vx/1E3;a.obj.y+=33*a.obj.vy/1E3}(-50>a.obj.x||-50>a.obj.y||a.obj.y>canvas.height+
50||a.obj.x>canvas.width+50)&&game.enemiesContainer.removeChild(a.obj);a.weapon.shoot(a.obj)};this.hit=function(c){a.obj.hp-=c.power;0>=a.obj.hp?a.obj.kill():(new Explosion(a.obj.x,a.obj.y),screenShake())};this.kill=function(){new Explosion(a.obj.x,a.obj.y);a.obj.hp=0;screenShake();a.obj.givePowerup&&new Powerup(a.obj);game.score+=a.obj.worth;game.level.score+=a.obj.worth;game.enemiesContainer.removeChild(a.obj);game.updateScore()}};
var Explosion=function(b,c){var a=new SpriteSheet({images:[game.preloader.getResult("explosion").src],frames:{width:128,height:128,regX:64,regY:64,count:72},animations:{explode:[0,71,!1,1]}}),a=new BitmapAnimation(a);a.x=b;a.y=c;game.explosionsContainer.addChild(a);a.gotoAndPlay("explode");a.tick=function(){this.x+=5;this.alpha-=0.1;0>=this.alpha&&game.explosionsContainer.removeChild(this)}};
var Game=function(){var a=this;a.stage={};a.canvas={};a.ctx={};a.loader={};a.preloader={};a.player={};a.paused=!1;a.playerBulletsContainer={};a.enemyBulletsContainer={};a.enemiesContainer={};a.explosionsContainer={};a.bossesContainer={};a.ticks=0;a.state="MAIN_MENU";a.level=1;a.currentLevel=1;a.score=0;a.bgCanvas={};a.bgCtx={};a.background={};a.stars=[];a.starSpeeds=[4,6,10];a.starColors=["#555","#aaa","#fff"];a.initStars=function(){for(var b=0;250>b;b++){var c=Math.floor(Math.random()*a.canvas.width),
d=Math.floor(Math.random()*a.canvas.height),e=Math.floor(3*Math.random());a.stars.push({x:c,y:d,speed:e})}};a.updateStars=function(){for(var b=0;b<a.stars.length;b++)a.stars[b].x-=a.starSpeeds[a.stars[b].speed],0>=a.stars[b].x&&(a.stars[b].y=Math.floor(Math.random()*a.canvas.height),a.stars[b].x=a.canvas.width);a.bgCtx.fillStyle="rgb(0,0,0)";a.bgCtx.fillRect(0,0,a.canvas.width,a.canvas.height);for(b=0;b<a.stars.length;b++)a.bgCtx.fillStyle=a.starColors[a.stars[b].speed],a.bgCtx.fillRect(a.stars[b].x,
a.stars[b].y,1,1)};a.onKeyDown=function(b){switch(b.keyCode){case 37:a.player.moveLeft=!0;a.player.moveRight=!1;break;case 38:a.player.moveUp=!0;a.player.moveDown=!1;break;case 39:a.player.moveRight=!0;a.player.moveLeft=!1;break;case 40:a.player.moveDown=!0;a.player.moveUp=!1;break;case 32:a.player.fireHeld=!0}};a.onKeyUp=function(b){switch(b.keyCode){case 37:a.player.moveLeft=!1;break;case 38:a.player.moveUp=!1;break;case 39:a.player.moveRight=!1;break;case 40:a.player.moveDown=!1;break;case 32:a.player.fireHeld=
!1}};a.init=function(){a.wrapper=document.getElementById("wrapper");a.loader=document.getElementById("loading");a.canvas=document.getElementById("canvas");a.bgCanvas=document.createElement("canvas");a.bgCanvas.style.position="absolute";a.bgCanvas.width=a.canvas.width;a.bgCanvas.height=a.canvas.height;wrapper.appendChild(a.bgCanvas);a.ctx=a.canvas.getContext("2d");a.bgCtx=a.bgCanvas.getContext("2d");a.stage=new Stage(a.canvas);Ticker.setFPS(30);Ticker.addListener(a.tick);document.onkeydown=a.onKeyDown;
document.onkeyup=a.onKeyUp;a.playerBulletsContainer=new Container;a.enemyBulletsContainer=new Container;a.enemiesContainer=new Container;a.explosionsContainer=new Container;a.powerupsContainer=new Container;a.textContainer=new Container;a.bossesContainer=new Container;a.stage.addChild(a.playerBulletsContainer,a.enemyBulletsContainer,a.enemiesContainer,a.explosionsContainer,a.powerupsContainer,a.textContainer,a.bossesContainer);a.setState("MAIN_MENU");a.levels=levels;loading.getElementsByTagName("div")[0].getElementsByTagName("div")[0].style.width=
"0px";$("#loading span").text(0);a.preloader=new PreloadJS(!0);a.preloader.onProgress=a.handleProgress;a.preloader.onComplete=a.loaded;a.preloader.onFileLoad=a.handleFileLoad;a.preloader.loadManifest([{id:"background",src:"./backgrounds/space.jpg"},{id:"orb",src:"./sprites/orb.png"},{id:"player-plane",src:"./sprites/player-single.png"},{id:"bullet-1",src:"./sprites/bullet2.png"},{id:"enemy-bullet",src:"./sprites/enemyBullet.png"},{id:"enemy-bullet-2",src:"sprites/enemyBullet2.png"},{id:"explosion",
src:"sprites/explosion.png"},{id:"power-1",src:"sprites/pow1.png"},{id:"orb-bullet",src:"sprites/bullet.png"}]);a.initStars()};a.setState=function(b){a.state=b;"PLAY"===a.state&&a.loadLevel()};a.gameover=function(){a.setState("MAIN_MENU");a.level={};a.currentLevel=1;a.score=0;a.updateScore();a.playerBulletsContainer.removeAllChildren();a.enemyBulletsContainer.removeAllChildren();a.enemiesContainer.removeAllChildren();a.explosionsContainer.removeAllChildren();a.powerupsContainer.removeAllChildren();
a.textContainer.removeAllChildren();a.bossesContainer.removeAllChildren();a.ticks=0;a.player.reset();$("#ui-bottom > ul > li").removeClass().eq(0).addClass("active");$("#main-menu").fadeIn(500)};a.loadLevel=function(){$("#main-menu").fadeOut(400);a.level=new Level;a.level.start(a.currentLevel)};a.handleProgress=function(){$("#loading span").text(100*a.preloader.progress|0);loading.getElementsByTagName("div")[0].getElementsByTagName("div")[0].style.width=(100*a.preloader.progress|0)+"%"};a.handleFileLoad=
function(b){$("#loading p").text(b.id);"player-plane"===b.id?a.playerLoaded():"background"===b.id&&(a.background=new Image,a.background.src=a.preloader.getResult("background").src,a.background.onload=a.renderBackground(),a.background.vx=0)};a.loaded=function(){$("#loading").fadeOut(10);$("#main-menu").fadeIn(0)};a.playerLoaded=function(){var b=new SpriteSheet({images:[a.preloader.getResult("player-plane").src],frames:{width:480,height:256,regX:240,regY:128},animations:{down:[3,4,"down"],up:[0,1,"up"],
none:[2,2,"none"]}});a.player=new Player(b);a.player.init()};a.tick=function(){if(!a.paused&&"PLAY"===a.state){a.updateStars();detectCollisions();a.level.tick();a.ticks++;a.player.tick();for(var b in a.enemiesContainer.children)a.enemiesContainer.children[b].tick();for(b in a.enemyBulletsContainer.children)a.enemyBulletsContainer.children[b].tick();for(b in a.explosionsContainer.children)a.explosionsContainer.children[b].tick();for(b in a.powerupsContainer.children)a.powerupsContainer.children[b].tick();
a.stage.update()}};a.renderBackground=function(){};a.updateScore=function(){document.getElementById("score").innerText=Utils.pad(game.score,10)}},Utils={randRange:function(a,b){return Math.random()*(b-a)+a},round:function(a,b){return Math.round(a*Math.pow(10,b))/Math.pow(10,b)},pad:function(a,b){for(var c=""+a;c.length<b;)c="0"+c;return c},toRad:function(a){return a*Math.PI/180}},enemies=[],timePassed=0;
function detectCollisions(){var a,b;if(game.player.active)for(var c in game.powerupsContainer.children)b=game.powerupsContainer.children[c],ndgmr.checkPixelCollision(b,game.player.obj)&&(game.powerupsContainer.removeChild(b),game.player.powerup());for(c in game.bossesContainer.children){boss=game.bossesContainer.children[c];game.player.active&&ndgmr.checkPixelCollision(boss,game.player.obj)&&(game.player.damage(),boss.hit(),0>=game.player.hp&&endGame());for(var d in game.playerBulletsContainer.children)if(b=
game.playerBulletsContainer.children[d],collision=b.x>game.canvas.width?!1:ndgmr.checkPixelCollision(b,boss))game.playerBulletsContainer.removeChild(b),boss.hit(b)}for(a in game.enemyBulletsContainer.children)b=game.enemyBulletsContainer.children[a],game.player.active&&ndgmr.checkPixelCollision(game.player.obj,b,0.2)&&(game.player.damage(),new Explosion(b.x,b.y),game.enemyBulletsContainer.removeChild(b),0>=game.player.hp&&endGame());for(c in game.enemiesContainer.children)for(d in a=game.enemiesContainer.children[c],
game.player.active&&ndgmr.checkPixelCollision(a,game.player.obj)&&(game.player.damage(),a.kill(),0>=game.player.hp&&endGame()),game.playerBulletsContainer.children)if(b=game.playerBulletsContainer.children[d],collision=b.x>game.canvas.width?!1:ndgmr.checkPixelCollision(b,a))game.level.bullets.hit++,game.playerBulletsContainer.removeChild(b),a.hit(b)}
function screenShake(){game.bgCanvas.style.top="-5px";setTimeout(function(){game.bgCanvas.style.top="-5px";game.bgCanvas.style.left="5px"},50);setTimeout(function(){game.bgCanvas.style.left="0";game.bgCanvas.style.top="0"},100)};
var Group=function(){this.enemies=[];this.interval;this.create=function(a){this.interval=a.interval;for(var b=0;b<a.count;b++){var c=new Enemy(a),d={x:a.params.x,y:a.params.y,speed:a.params.speed,startAngle:Utils.toRad(a.params.angle),angleToRotate:Utils.toRad(a.params.rotateAngle),rotateSpeed:a.params.rotateSpeed,trajectory:a.trajectory,distance:a.params.distance,init:game.level.levelTimer+this.interval+b};c.init(d);this.enemies.push(c)}}};
var Level=function(){this.current;this.data;this.state="";this.enemiesGroupIndex=this.levelTimer=0;this.enemiesToCreate=[];this.boss=!1;this.score=0;this.levelComplete=!1;this.bullets={fired:0,hit:0};var d=this;this.start=function(b){this.current=b;this.data=levels[this.current-1]};this.tick=function(){this.levelTimer+=0.03;this.createEnemies();this.createTimedEnemies();this.removeObjects();this.uiUpdate();this.boss&&this.boss.tick();this.checkComplete()};this.checkComplete=function(){if("COMPLETE"===
this.state){this.state="INTERVAL";var b=new Text("Level Score: "+game.level.score,"24pt bold Monospace","#fff");b.textAlign="center";b.x=400;b.y=200;b.alpha=1;b.init=game.ticks;var a=Math.floor(100*(this.bullets.hit/this.bullets.fired)),c=new Text("Accuracy: "+a+"%","24pt bold Monospace","#fff");c.textAlign="center";c.x=450;c.y=250;c.alpha=1;c.init=game.ticks;var e=0;25>a?e=0:25<a?e=100:50<a?e=250:75<a?e=500:100==a&&(e=1E3);a=new Text("Bonus: "+e,"24pt bold Monospace","#fff");a.textAlign="center";
a.x=500;a.y=300;a.alpha=1;a.init=game.ticks;game.score+=e;game.updateScore();game.textContainer.addChild(b);game.textContainer.addChild(c);game.textContainer.addChild(a);levels[d.current]?setTimeout(function(){this.state="";game.currentLevel=d.current+1;game.loadLevel()},5E3):(this.levelTimer=0,game.gameover())}};this.uiUpdate=function(){var b=["yellow","orange","white","red"],a;for(a in game.textContainer.children){var c=game.textContainer.children[a];c.y-=1;c.color=b[Math.floor(Utils.randRange(0,
b.length-1))];c.alpha-=0.009;0>=c.alpha&&game.textContainer.removeChild(c)}};this.createTimedEnemies=function(){for(var b=[],a=0;a<this.enemiesToCreate.length;a++){enemyData=this.enemiesToCreate[a];if(enemyData.init+enemyData.interval==game.ticks){var c=enemyData.enemies.shift();game.enemiesContainer.addChild(c.obj);enemyData.init=game.ticks}0==enemyData.enemies.length&&b.push(enemyData)}for(a=0;a<b.length;a++)this.enemiesToCreate.splice(this.enemiesToCreate.indexOf(b[a]),1),b[a]=null};this.createEnemies=
function(){if(this.enemiesGroupIndex<this.data.length){if(30*this.data[this.enemiesGroupIndex].time<=game.ticks){var b=new Group;b.create(this.data[this.enemiesGroupIndex]);this.enemiesToCreate.push({enemies:b.enemies,interval:30*b.interval,maxInterval:30*b.interval,init:game.ticks});this.enemiesGroupIndex++}}else!d.boss&&"PLAY"==game.state&&(0==this.enemiesToCreate.length&&0==game.enemiesContainer.children.length)&&("null"!=bosses[d.current-1]?(d.boss=new Boss(d.current-1),game.bossesContainer.addChild(d.boss.boss.obj)):
d.state="COMPLETE")};this.removeObjects=function(){var b=[],a;for(a in game.enemiesContainer.children)0>=game.enemiesContainer.children[a].hp&&b.push(game.enemiesContainer.children[a]);for(var c in b)game.enemiesContainer.removeChild(b[c])}};
var levels=[[{time:1,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:640,y:240,angle:180,speed:350,distance:200,rotateAngle:270,rotateSpeed:0.3}},{time:6,enemyClass:"orb",count:4,interval:0.5,trajectory:"ROTATION",params:{x:640,y:100,angle:180,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:8,enemyClass:"orb2",count:1,interval:0.5,trajectory:"ROTATION",params:{x:640,y:100,angle:180,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:6,enemyClass:"orb",count:5,
interval:0.5,trajectory:"ROTATION",params:{x:640,y:380,angle:180,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:11,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:640,y:350,angle:180,speed:350,distance:300,rotateAngle:180,rotateSpeed:0.1}},{time:16,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:300,y:0,angle:90,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:20,enemyClass:"orb",count:4,interval:0.5,trajectory:"ROTATION",params:{x:500,
y:480,angle:270,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:22,enemyClass:"orb2",count:1,interval:0.5,trajectory:"ROTATION",params:{x:500,y:480,angle:270,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}}],[{time:1,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:320,y:0,angle:90,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}}]];
var levels=[[{time:1,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:640,y:240,angle:180,speed:350,distance:200,rotateAngle:270,rotateSpeed:0.3}}],[{time:1,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:320,y:0,angle:90,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}}]];
var Player=function(){var a=this;a.init=function(){a.obj={};a.special=1;a.hp=50;a.speed=1;a.img="";a.fireHeld=!1;a.obj=new Bitmap(game.preloader.getResult("player-plane").src);a.obj.x=80;a.obj.y=240;a.obj.scaleX=1;a.obj.scaleY=1;a.lastBullet=0;a.orbs=[];a.moveUp=!1;a.moveDown=!1;a.moveLeft=!1;a.moveRight=!1;a.active=!0;game.stage.addChild(a.obj)};a.damage=function(){a.hp--;a.special=1;screenShake();a.active=!1;a.obj.x=-100;setTimeout(function(){a.respawn=!0},1E3);if(a.orbs.length)for(var b=0;b<a.orbs.length;b++)a.orbs[b].kill();
$("#ui-bottom > ul > li").removeClass().eq(0).addClass("active")};a.fire=function(){if(!a.active)return!1;if(a.lastBullet<(new Date).getTime()-150&&15>game.playerBulletsContainer.children.length){if(a.orbs.length)for(var b in a.orbs)a.orbs[b].fire();switch(a.special){case 1:case 2:b=new Bitmap(game.preloader.getResult("bullet-1").src);b.x=a.obj.x+a.obj.regX;b.y=a.obj.y-a.obj.regY;b.power=1;game.level.bullets.fired++;game.playerBulletsContainer.addChild(b);break;case 3:case 4:b=new Bitmap(game.preloader.getResult("bullet-1").src);
b.x=a.obj.x+a.obj.regX;b.y=a.obj.y-a.obj.regY+10;b.power=1;game.level.bullets.fired++;var c=new Bitmap(game.preloader.getResult("bullet-1").src);c.x=a.obj.x+a.obj.regX;c.y=a.obj.y-a.obj.regY-10;c.power=1;game.playerBulletsContainer.addChild(b);game.playerBulletsContainer.addChild(c);break;case 5:b=new Bitmap(game.preloader.getResult("bullet-1").src),b.x=a.obj.x+a.obj.regX+20,b.y=a.obj.y-a.obj.regY,b.power=1,game.level.bullets.fired++,c=new Bitmap(game.preloader.getResult("bullet-1").src),c.x=a.obj.x+
a.obj.regX+40,c.y=a.obj.y-a.obj.regY+35,c.power=1,c.rotation=-45,game.playerBulletsContainer.addChild(b),game.playerBulletsContainer.addChild(c)}a.lastBullet=(new Date).getTime()}};a.createOrb=function(){if(1==a.orbs.length)return!1;var b=new Bitmap(game.preloader.getResult("orb").src);b.scaleX=b.scaleY=1;b.kill=function(){a.orbs.splice(b,1);game.stage.removeChild(b)};b.fire=function(){var a=new Bitmap(game.preloader.getResult("orb-bullet").src);a.x=b.x;a.y=b.y;a.power=0.5;a.scaleX=a.scaleY=0.5;game.playerBulletsContainer.addChild(a)};
a.orbs.push(b);game.stage.addChild(b)};a.reset=function(){game.stage.removeChild(a.obj);if(a.orbs.length)for(var b in a.orbs)a.orbs[b].kill();a.init()};a.updateBullets=function(){for(var a in game.playerBulletsContainer.children){var c=game.playerBulletsContainer.children[a];c.x+=30;0!=c.rotation&&(c.y+=-30);game.playerBulletsContainer.children[a].x>game.canvas.width+50&&game.playerBulletsContainer.removeChild(game.playerBulletsContainer.children[a])}};a.powerup=function(){a.special++;if(0<a.special)switch(5<
a.special&&(a.special=5),a.special){case 2:a.createOrb()}$("#ui-bottom > ul > li").removeClass().eq(a.special-1).addClass("active")};a.tick=function(){a.respawn&&(a.obj.alpha=0==game.ticks%2?1:0,a.obj.x+=5,a.obj.y=240,200<=a.obj.x&&(a.obj.alpha=1,a.respawn=!1,a.active=!0));a.active&&(a.moveLeft?(a.obj.x-=10,0>=a.obj.x&&(a.obj.x=0)):a.moveRight&&(a.obj.x+=10,740<a.obj.x&&(a.obj.x=740)),a.moveUp?60<a.obj.y-10&&(a.obj.y-=10):a.moveDown&&420>a.obj.y+10&&(a.obj.y+=10),a.fireHeld&&a.fire());a.updateBullets();
if(a.orbs.length)for(var b in a.orbs){var c=a.orbs[b];c.offsetX=10*Math.cos(game.ticks/10)*b;c.offsetY=5*Math.sin(game.ticks/7);c.x=c.x+0.1*(a.obj.x-c.x)+c.offsetX;c.y=c.y+0.1*(a.obj.y-c.y)+c.offsetY}}};
var Powerup=function(b){var a=new Bitmap(game.preloader.getResult("power-1").src);a.x=b.x;a.y=b.y-10;a.regX=a.width/2;a.regY=a.height/2;game.powerupsContainer.addChild(a);a.tick=function(){if(game.powerupsContainer.children.length){var a=game.powerupsContainer.children[0];a.x-=2;-50>a.x&&game.powerupsContainer.removeChild(a)}}};
var Weapon=function(a){this.obj={};switch(a){case "SINGLELINEAR":return new SingleLinear;case "SINGLEDIRECTIONAL":return new SingleDirectional}};
var SingleDirectional=function(){this.obj=new Bitmap(game.preloader.getResult("enemy-bullet-2").src);this.interval=Utils.randRange(1.2,1.7);var a=this;this.direction=180;this.angle;this.obj.velocity={x:-20,y:0};this.shoot=function(b){this.interval-=0.03;0>=this.interval&&(a.direction=Math.atan2(game.player.obj.y-b.y,game.player.obj.x-b.x)*(180/Math.PI),game.enemyBulletsContainer.addChild(this.obj),a.obj.x=b.x,a.obj.y=b.y,a.angle=a.direction*Math.PI/180,a.obj.rotation=a.direction+Math.PI+180,a.obj.velocity=
{x:20*Math.cos(a.angle),y:20*Math.sin(a.angle)},this.interval=Utils.randRange(1.2,1.7))};this.obj.tick=function(){a.obj.x+=a.obj.velocity.x;a.obj.y+=a.obj.velocity.y;-150>a.obj.x&&game.enemyBulletsContainer.removeChild(a.obj)}};
var SingleLinear=function(){this.obj=new Bitmap(game.preloader.getResult("enemy-bullet").src);this.interval=Utils.randRange(1,1.5);var a=this;this.obj.velocity={x:-20,y:0};this.shoot=function(a,b,c){this.interval-=0.03;b||(b=a.x-a.regX);c||(c=a.y-a.regY);0>=this.interval&&(this.obj.x=b,this.obj.y=c,game.enemyBulletsContainer.addChild(this.obj),this.interval=Utils.randRange(1,1.5))};this.obj.tick=function(){a.obj.x+=a.obj.velocity.x;a.obj.y+=a.obj.velocity.y;0>a.obj.x&&game.enemyBulletsContainer.removeChild(a.obj)}};
var Boss=function(a){this.boss=new window[bosses[a]];this.hit=this.boss.hit;this.tick=function(){this.boss.tick()}};
var bosses=["Boss1","null"];
this.ndgmr=this.ndgmr||{};
(function(){var p=document.createElement("canvas"),t=p.getContext("2d");t.save();var q=document.createElement("canvas"),u=q.getContext("2d");u.save();var s=[],w=function(a,b){var d,e;d=j(a);e=j(b);return v(d,e)};ndgmr.checkRectCollision=w;ndgmr.checkPixelCollision=function(a,b,d,e){if(ndgmr.DEBUG||ndgmr.DEBUG_COLLISION)document.body.appendChild(p),document.body.appendChild(q);e=e||!1;var c,g;c=a instanceof createjs.Bitmap?{width:a.image.width,height:a.image.height}:a.spriteSheet.getFrame(a.currentFrame).rect;g=
b instanceof createjs.Bitmap?{width:b.image.width,height:b.image.height}:b.spriteSheet.getFrame(b.currentFrame).rect;if(!(Math.abs(b.x-a.x)<g.width*b.scaleX+c.width*a.scaleX&&Math.abs(b.y-a.y)<g.height*b.scaleY+c.height*b.scaleY))return!1;c=w(a,b);if(!c)return!1;d=Math.min(0.99999,d||0);p.width=c.width;p.height=c.height;q.width=c.width;q.height=c.height;a=x(c,a,t);a:{b=x(c,b,u);g=c.width;var j=c.height,m,n,h,k,l=3,f={x:Infinity,y:Infinity,x2:-Infinity,y2:-Infinity};for(k=0;k<j;++k)for(h=0;h<g;++h){m=
a.length>l+1?a[l]/255:0;n=b.length>l+1?b[l]/255:0;if(m>d&&n>d)if(e)h<f.x&&(f.x=h),h>f.x2&&(f.x2=h),k<f.y&&(f.y=k),k>f.y2&&(f.y2=k);else{a={x:h,y:k,width:1,height:1};break a}l+=4}Infinity!=f.x?(f.width=f.x2-f.x+1,f.height=f.y2-f.y+1,a=f):a=null}if(a)a.x+=c.x,a.x2+=c.x,a.y+=c.y,a.y2+=c.y;else return!1;return a};var x=function(a,b,d){var e,c;b instanceof createjs.Bitmap?c=b.image:b instanceof createjs.BitmapAnimation&&(e=b.currentFrame+b.spriteSheet.getFrame(b.currentFrame).image.src,s[e]?c=s[e]:s[e]=
c=createjs.SpriteSheetUtils.extractFrame(b.spriteSheet,b.currentFrame));e=b.globalToLocal(a.x,a.y);d.restore();d.clearRect(0,0,a.width,a.height);d.rotate(r(b,"rotation")*(Math.PI/180));d.scale(r(b,"scaleX","*"),r(b,"scaleY","*"));d.translate(-e.x,-e.y);d.drawImage(c,0,0,c.width,c.height);return d.getImageData(0,0,a.width,a.height).data},r=function(a,b,d){d=d||"+";if(a.parent&&a.parent[b]){var e=a[b];a=r(a.parent,b,d);return"*"==d?e*a:e+a}return a[b]},v=function(a,b){var d,e,c,g,j,m,n,h;d=a.x+(c=a.width/
2);e=a.y+(g=a.height/2);j=b.x+(m=b.width/2);n=b.y+(h=b.height/2);d=Math.abs(d-j)-(c+m);e=Math.abs(e-n)-(g+h);return 0>d&&0>e?(d=Math.min(Math.min(a.width,b.width),-d),e=Math.min(Math.min(a.height,b.height),-e),{x:Math.max(a.x,b.x),y:Math.max(a.y,b.y),width:d,height:e}):null};ndgmr.calculateIntersection=v;var j=function(a){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){var d=a.children,e=d.length,c;for(a=0;a<e;a++)c=j(d[a]),c.x<b.x&&(b.x=c.x),c.y<b.y&&(b.y=c.y),
c.width>b.width&&(b.width=c.width),c.height>b.height&&(b.height=c.height)}else{var g;if(a instanceof createjs.Bitmap)g=a.image;else if(a instanceof createjs.BitmapAnimation)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image)g=a.spriteSheet.getFrame(a.currentFrame).rect;else return b;else return b;d=a.localToGlobal(0,0);e=a.localToGlobal(g.width,g.height);c=a.localToGlobal(g.width,0);a=a.localToGlobal(0,g.height);b.x=Math.min(Math.min(Math.min(d.x,
e.x),c.x),a.x);b.y=Math.min(Math.min(Math.min(d.y,e.y),c.y),a.y);b.width=Math.max(Math.max(Math.max(d.x,e.x),c.x),a.x)-b.x;b.height=Math.max(Math.max(Math.max(d.y,e.y),c.y),a.y)-b.y}return b};ndgmr.getBounds=j})();
window.Boss1=function(){this.obj=new Bitmap("./sprites/enemies/bosses/boss1.png");this.obj.state=2;this.obj.speed=10;this.obj.x=640;this.obj.y=240;this.obj.vx=-50;this.obj.vy=0;this.obj.hp=200;this.obj.worth=500;this.obj.weapon1=new Weapon("SINGLELINEAR");this.obj.weapon2=new Weapon("SINGLEDIRECTIONAL");this.obj.dead=!1;var a=this;this.obj.hit=function(){a.obj.hp--;0>=a.obj.hp&&(a.obj.dead=!0,new Explosion(a.obj.x-20,a.obj.y),new Explosion(a.obj.x,a.obj.y-20),new Explosion(a.obj.x+20,a.obj.y+20),
a.obj.state=3,game.score+=a.obj.worth,game.level.score+=a.obj.worth,game.updateScore(),game.bossesContainer.removeChild(a.obj),game.level.state="COMPLETE")};this.tick=function(){if(a.obj.dead)return!1;switch(a.obj.state){case 0:a.obj.x+=33*a.obj.vx/1E3;a.obj.y+=33*a.obj.vy/1E3;break;case 1:a.obj.vx=50*Math.cos(0.05*a.obj.speed);a.obj.speed++;a.obj.x+=33*a.obj.vx/1E3;a.obj.y+=33*a.obj.vy/1E3;a.obj.y+a.obj.image.height>game.canvas.height&&(a.obj.y=game.canvas.height-a.obj.image.height,a.obj.vy*=-1);
0>a.obj.y&&(a.obj.y=0,a.obj.vy*=-1);a.obj.weapon1.shoot(this.obj,null,a.obj.y-a.obj.regY+20);a.obj.weapon2.shoot(this.obj);break;case 2:0<a.obj.hp&&setTimeout(function(){a.obj.state=0},3E3)}0==a.obj.state&&450>=a.obj.x&&(a.obj.vx=0,a.obj.vy=80,a.obj.state=1)}};
var OrbEnemy=function(){this.sprite="orb.png";this.height=this.width=25;this.bullet="enemyBullet.png";this.fire=!0;this.speed=15;this.hp=1;this.worth=100;this.givePowerup=!1;this.powerupImage=null;this.isRotating=!0;this.weapon="SINGLELINEAR"};
var Orb2Enemy=function(){this.sprite="orb2.png";this.height=this.width=25;this.bullet="enemyBullet.png";this.fire=!0;this.speed=15;this.hp=1;this.worth=100;this.givePowerup=!0;this.powerupImage=null;this.isRotating=!0;this.weapon="SINGLEDIRECTIONAL"};
var Enemy=function(d){this.obj={};var a=this;this.data=d;this.init=function(a){switch(this.data.enemyClass){case "orb":var b=new OrbEnemy;break;case "orb2":b=new Orb2Enemy}this.obj=new Bitmap("./sprites/enemies/"+b.sprite);this.obj.x=a.x;this.obj.y=a.y;this.obj.init=a.init;this.obj.regX=b.width/2;this.obj.regY=b.height/2;this.obj.bullet=b.bullet;this.obj.scaleX=1;this.obj.scaleY=1;this.obj.firer=b.fire;this.obj.speed=a.speed;this.obj.hp=b.hp;this.obj.givePowerup=b.givePowerup;this.obj.powerupImage=
b.powerupImage;this.obj.worth=b.worth;this.obj.rtData=a;this.obj.tick=this.tick;this.obj.hit=this.hit;this.obj.kill=this.kill;this.obj.fire=this.fire;this.obj.isRotating=b.isRotating;this.obj.state=0;this.obj.angle=a.startAngle;this.weapon=new Weapon(b.weapon)};this.tick=function(){switch(a.obj.rtData.trajectory){case "ROTATION":if(0==a.obj.state){var c=a.obj.x-a.obj.rtData.x,b=a.obj.y-a.obj.rtData.y,c=Math.sqrt(c*c+b*b);0>=a.obj.rtData.distance-c&&(a.obj.state=1)}1==a.obj.state&&(a.obj.angle+=a.obj.rtData.rotateSpeed);
1==a.obj.state&&Math.abs(a.obj.angle-a.obj.rtData.startAngle)>=a.obj.rtData.angleToRotate&&(a.obj.angle=0>a.obj.rtData.rotateSpeed?a.obj.angle+(Math.abs(a.obj.angle-a.obj.rtData.startAngle)-a.obj.rtData.angleToRotate):a.obj.angle-(Math.abs(a.obj.angle-a.obj.rtData.startAngle)-a.obj.rtData.angleToRotate),a.obj.state=2);a.obj.vx=Math.cos(a.obj.angle)*a.obj.speed;a.obj.vy=Math.sin(a.obj.angle)*a.obj.speed;a.obj.x+=33*a.obj.vx/1E3;a.obj.y+=33*a.obj.vy/1E3}(-50>a.obj.x||-50>a.obj.y||a.obj.y>canvas.height+
50||a.obj.x>canvas.width+50)&&game.enemiesContainer.removeChild(a.obj);a.weapon.shoot(a.obj)};this.hit=function(c){a.obj.hp-=c.power;0>=a.obj.hp?a.obj.kill():(new Explosion(a.obj.x,a.obj.y),screenShake())};this.kill=function(){new Explosion(a.obj.x,a.obj.y);a.obj.hp=0;screenShake();a.obj.givePowerup&&new Powerup(a.obj);game.score+=a.obj.worth;game.level.score+=a.obj.worth;game.enemiesContainer.removeChild(a.obj);game.updateScore()}};
var Explosion=function(b,c){var a=new SpriteSheet({images:[game.preloader.getResult("explosion").src],frames:{width:128,height:128,regX:64,regY:64,count:72},animations:{explode:[0,71,!1,1]}}),a=new BitmapAnimation(a);a.x=b;a.y=c;game.explosionsContainer.addChild(a);a.gotoAndPlay("explode");a.tick=function(){this.x+=5;this.alpha-=0.1;0>=this.alpha&&game.explosionsContainer.removeChild(this)}};
var Game=function(){var a=this;a.stage={};a.canvas={};a.ctx={};a.loader={};a.preloader={};a.player={};a.paused=!1;a.playerBulletsContainer={};a.enemyBulletsContainer={};a.enemiesContainer={};a.explosionsContainer={};a.bossesContainer={};a.ticks=0;a.state="MAIN_MENU";a.level=1;a.currentLevel=1;a.score=0;a.bgCanvas={};a.bgCtx={};a.background={};a.stars=[];a.starSpeeds=[4,6,10];a.starColors=["#555","#aaa","#fff"];a.initStars=function(){for(var b=0;250>b;b++){var c=Math.floor(Math.random()*a.canvas.width),
d=Math.floor(Math.random()*a.canvas.height),e=Math.floor(3*Math.random());a.stars.push({x:c,y:d,speed:e})}};a.updateStars=function(){for(var b=0;b<a.stars.length;b++)a.stars[b].x-=a.starSpeeds[a.stars[b].speed],0>=a.stars[b].x&&(a.stars[b].y=Math.floor(Math.random()*a.canvas.height),a.stars[b].x=a.canvas.width);a.bgCtx.fillStyle="rgb(0,0,0)";a.bgCtx.fillRect(0,0,a.canvas.width,a.canvas.height);for(b=0;b<a.stars.length;b++)a.bgCtx.fillStyle=a.starColors[a.stars[b].speed],a.bgCtx.fillRect(a.stars[b].x,
a.stars[b].y,1,1)};a.onKeyDown=function(b){switch(b.keyCode){case 37:a.player.moveLeft=!0;a.player.moveRight=!1;break;case 38:a.player.moveUp=!0;a.player.moveDown=!1;break;case 39:a.player.moveRight=!0;a.player.moveLeft=!1;break;case 40:a.player.moveDown=!0;a.player.moveUp=!1;break;case 32:a.player.fireHeld=!0}};a.onKeyUp=function(b){switch(b.keyCode){case 37:a.player.moveLeft=!1;break;case 38:a.player.moveUp=!1;break;case 39:a.player.moveRight=!1;break;case 40:a.player.moveDown=!1;break;case 32:a.player.fireHeld=
!1}};a.init=function(){a.wrapper=document.getElementById("wrapper");a.loader=document.getElementById("loading");a.canvas=document.getElementById("canvas");a.bgCanvas=document.createElement("canvas");a.bgCanvas.style.position="absolute";a.bgCanvas.width=a.canvas.width;a.bgCanvas.height=a.canvas.height;wrapper.appendChild(a.bgCanvas);a.ctx=a.canvas.getContext("2d");a.bgCtx=a.bgCanvas.getContext("2d");a.stage=new Stage(a.canvas);Ticker.setFPS(30);Ticker.addListener(a.tick);document.onkeydown=a.onKeyDown;
document.onkeyup=a.onKeyUp;a.playerBulletsContainer=new Container;a.enemyBulletsContainer=new Container;a.enemiesContainer=new Container;a.explosionsContainer=new Container;a.powerupsContainer=new Container;a.textContainer=new Container;a.bossesContainer=new Container;a.stage.addChild(a.playerBulletsContainer,a.enemyBulletsContainer,a.enemiesContainer,a.explosionsContainer,a.powerupsContainer,a.textContainer,a.bossesContainer);a.setState("MAIN_MENU");a.levels=levels;loading.getElementsByTagName("div")[0].getElementsByTagName("div")[0].style.width=
"0px";$("#loading span").text(0);a.preloader=new PreloadJS(!0);a.preloader.onProgress=a.handleProgress;a.preloader.onComplete=a.loaded;a.preloader.onFileLoad=a.handleFileLoad;a.preloader.loadManifest([{id:"background",src:"./backgrounds/space.jpg"},{id:"orb",src:"./sprites/orb.png"},{id:"player-plane",src:"./sprites/player-single.png"},{id:"bullet-1",src:"./sprites/bullet2.png"},{id:"enemy-bullet",src:"./sprites/enemyBullet.png"},{id:"enemy-bullet-2",src:"sprites/enemyBullet2.png"},{id:"explosion",
src:"sprites/explosion.png"},{id:"power-1",src:"sprites/pow1.png"},{id:"orb-bullet",src:"sprites/bullet.png"}]);a.initStars()};a.setState=function(b){a.state=b;"PLAY"===a.state&&a.loadLevel()};a.gameover=function(){a.setState("MAIN_MENU");a.level={};a.currentLevel=1;a.score=0;a.updateScore();a.playerBulletsContainer.removeAllChildren();a.enemyBulletsContainer.removeAllChildren();a.enemiesContainer.removeAllChildren();a.explosionsContainer.removeAllChildren();a.powerupsContainer.removeAllChildren();
a.textContainer.removeAllChildren();a.bossesContainer.removeAllChildren();a.ticks=0;a.player.reset();$("#ui-bottom > ul > li").removeClass().eq(0).addClass("active");$("#main-menu").fadeIn(500)};a.loadLevel=function(){$("#main-menu").fadeOut(400);a.level=new Level;a.level.start(a.currentLevel)};a.handleProgress=function(){$("#loading span").text(100*a.preloader.progress|0);loading.getElementsByTagName("div")[0].getElementsByTagName("div")[0].style.width=(100*a.preloader.progress|0)+"%"};a.handleFileLoad=
function(b){$("#loading p").text(b.id);"player-plane"===b.id?a.playerLoaded():"background"===b.id&&(a.background=new Image,a.background.src=a.preloader.getResult("background").src,a.background.onload=a.renderBackground(),a.background.vx=0)};a.loaded=function(){$("#loading").fadeOut(10);$("#main-menu").fadeIn(0)};a.playerLoaded=function(){var b=new SpriteSheet({images:[a.preloader.getResult("player-plane").src],frames:{width:480,height:256,regX:240,regY:128},animations:{down:[3,4,"down"],up:[0,1,"up"],
none:[2,2,"none"]}});a.player=new Player(b);a.player.init()};a.tick=function(){if(!a.paused&&"PLAY"===a.state){a.updateStars();detectCollisions();a.level.tick();a.ticks++;a.player.tick();for(var b in a.enemiesContainer.children)a.enemiesContainer.children[b].tick();for(b in a.enemyBulletsContainer.children)a.enemyBulletsContainer.children[b].tick();for(b in a.explosionsContainer.children)a.explosionsContainer.children[b].tick();for(b in a.powerupsContainer.children)a.powerupsContainer.children[b].tick();
a.stage.update()}};a.renderBackground=function(){};a.updateScore=function(){document.getElementById("score").innerText=Utils.pad(game.score,10)}},Utils={randRange:function(a,b){return Math.random()*(b-a)+a},round:function(a,b){return Math.round(a*Math.pow(10,b))/Math.pow(10,b)},pad:function(a,b){for(var c=""+a;c.length<b;)c="0"+c;return c},toRad:function(a){return a*Math.PI/180}},enemies=[],timePassed=0;
function detectCollisions(){var a,b;if(game.player.active)for(var c in game.powerupsContainer.children)b=game.powerupsContainer.children[c],ndgmr.checkPixelCollision(b,game.player.obj)&&(game.powerupsContainer.removeChild(b),game.player.powerup());for(c in game.bossesContainer.children){boss=game.bossesContainer.children[c];game.player.active&&ndgmr.checkPixelCollision(boss,game.player.obj)&&(game.player.damage(),boss.hit(),0>=game.player.hp&&endGame());for(var d in game.playerBulletsContainer.children)if(b=
game.playerBulletsContainer.children[d],collision=b.x>game.canvas.width?!1:ndgmr.checkPixelCollision(b,boss))game.playerBulletsContainer.removeChild(b),boss.hit(b)}for(a in game.enemyBulletsContainer.children)b=game.enemyBulletsContainer.children[a],game.player.active&&ndgmr.checkPixelCollision(game.player.obj,b,0.2)&&(game.player.damage(),new Explosion(b.x,b.y),game.enemyBulletsContainer.removeChild(b),0>=game.player.hp&&endGame());for(c in game.enemiesContainer.children)for(d in a=game.enemiesContainer.children[c],
game.player.active&&ndgmr.checkPixelCollision(a,game.player.obj)&&(game.player.damage(),a.kill(),0>=game.player.hp&&endGame()),game.playerBulletsContainer.children)if(b=game.playerBulletsContainer.children[d],collision=b.x>game.canvas.width?!1:ndgmr.checkPixelCollision(b,a))game.level.bullets.hit++,game.playerBulletsContainer.removeChild(b),a.hit(b)}
function screenShake(){game.bgCanvas.style.top="-5px";setTimeout(function(){game.bgCanvas.style.top="-5px";game.bgCanvas.style.left="5px"},50);setTimeout(function(){game.bgCanvas.style.left="0";game.bgCanvas.style.top="0"},100)};
var Group=function(){this.enemies=[];this.interval;this.create=function(a){this.interval=a.interval;for(var b=0;b<a.count;b++){var c=new Enemy(a),d={x:a.params.x,y:a.params.y,speed:a.params.speed,startAngle:Utils.toRad(a.params.angle),angleToRotate:Utils.toRad(a.params.rotateAngle),rotateSpeed:a.params.rotateSpeed,trajectory:a.trajectory,distance:a.params.distance,init:game.level.levelTimer+this.interval+b};c.init(d);this.enemies.push(c)}}};
var Level=function(){this.current;this.data;this.state="";this.enemiesGroupIndex=this.levelTimer=0;this.enemiesToCreate=[];this.boss=!1;this.score=0;this.levelComplete=!1;this.bullets={fired:0,hit:0};var d=this;this.start=function(b){this.current=b;this.data=levels[this.current-1]};this.tick=function(){this.levelTimer+=0.03;this.createEnemies();this.createTimedEnemies();this.removeObjects();this.uiUpdate();this.boss&&this.boss.tick();this.checkComplete()};this.checkComplete=function(){if("COMPLETE"===
this.state){this.state="INTERVAL";var b=new Text("Level Score: "+game.level.score,"24pt bold Monospace","#fff");b.textAlign="center";b.x=400;b.y=200;b.alpha=1;b.init=game.ticks;var a=Math.floor(100*(this.bullets.hit/this.bullets.fired)),c=new Text("Accuracy: "+a+"%","24pt bold Monospace","#fff");c.textAlign="center";c.x=450;c.y=250;c.alpha=1;c.init=game.ticks;var e=0;25>a?e=0:25<a?e=100:50<a?e=250:75<a?e=500:100==a&&(e=1E3);a=new Text("Bonus: "+e,"24pt bold Monospace","#fff");a.textAlign="center";
a.x=500;a.y=300;a.alpha=1;a.init=game.ticks;game.score+=e;game.updateScore();game.textContainer.addChild(b);game.textContainer.addChild(c);game.textContainer.addChild(a);levels[d.current]?setTimeout(function(){this.state="";game.currentLevel=d.current+1;game.loadLevel()},5E3):(this.levelTimer=0,game.gameover())}};this.uiUpdate=function(){var b=["yellow","orange","white","red"],a;for(a in game.textContainer.children){var c=game.textContainer.children[a];c.y-=1;c.color=b[Math.floor(Utils.randRange(0,
b.length-1))];c.alpha-=0.009;0>=c.alpha&&game.textContainer.removeChild(c)}};this.createTimedEnemies=function(){for(var b=[],a=0;a<this.enemiesToCreate.length;a++){enemyData=this.enemiesToCreate[a];if(enemyData.init+enemyData.interval==game.ticks){var c=enemyData.enemies.shift();game.enemiesContainer.addChild(c.obj);enemyData.init=game.ticks}0==enemyData.enemies.length&&b.push(enemyData)}for(a=0;a<b.length;a++)this.enemiesToCreate.splice(this.enemiesToCreate.indexOf(b[a]),1),b[a]=null};this.createEnemies=
function(){if(this.enemiesGroupIndex<this.data.length){if(30*this.data[this.enemiesGroupIndex].time<=game.ticks){var b=new Group;b.create(this.data[this.enemiesGroupIndex]);this.enemiesToCreate.push({enemies:b.enemies,interval:30*b.interval,maxInterval:30*b.interval,init:game.ticks});this.enemiesGroupIndex++}}else!d.boss&&"PLAY"==game.state&&(0==this.enemiesToCreate.length&&0==game.enemiesContainer.children.length)&&("null"!=bosses[d.current-1]?(d.boss=new Boss(d.current-1),game.bossesContainer.addChild(d.boss.boss.obj)):
d.state="COMPLETE")};this.removeObjects=function(){var b=[],a;for(a in game.enemiesContainer.children)0>=game.enemiesContainer.children[a].hp&&b.push(game.enemiesContainer.children[a]);for(var c in b)game.enemiesContainer.removeChild(b[c])}};
var levels=[[{time:1,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:640,y:240,angle:180,speed:350,distance:200,rotateAngle:270,rotateSpeed:0.3}},{time:6,enemyClass:"orb",count:4,interval:0.5,trajectory:"ROTATION",params:{x:640,y:100,angle:180,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:8,enemyClass:"orb2",count:1,interval:0.5,trajectory:"ROTATION",params:{x:640,y:100,angle:180,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:6,enemyClass:"orb",count:5,
interval:0.5,trajectory:"ROTATION",params:{x:640,y:380,angle:180,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:11,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:640,y:350,angle:180,speed:350,distance:300,rotateAngle:180,rotateSpeed:0.1}},{time:16,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:300,y:0,angle:90,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:20,enemyClass:"orb",count:4,interval:0.5,trajectory:"ROTATION",params:{x:500,
y:480,angle:270,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}},{time:22,enemyClass:"orb2",count:1,interval:0.5,trajectory:"ROTATION",params:{x:500,y:480,angle:270,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}}],[{time:1,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:320,y:0,angle:90,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}}]];
var levels=[[{time:1,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:640,y:240,angle:180,speed:350,distance:200,rotateAngle:270,rotateSpeed:0.3}}],[{time:1,enemyClass:"orb",count:5,interval:0.5,trajectory:"ROTATION",params:{x:320,y:0,angle:90,speed:350,distance:200,rotateAngle:0,rotateSpeed:0.3}}]];
var Player=function(){var a=this;a.init=function(){a.obj={};a.special=1;a.hp=50;a.speed=1;a.img="";a.fireHeld=!1;a.obj=new Bitmap(game.preloader.getResult("player-plane").src);a.obj.x=80;a.obj.y=240;a.obj.scaleX=1;a.obj.scaleY=1;a.lastBullet=0;a.orbs=[];a.moveUp=!1;a.moveDown=!1;a.moveLeft=!1;a.moveRight=!1;a.active=!0;game.stage.addChild(a.obj)};a.damage=function(){a.hp--;a.special=1;screenShake();a.active=!1;a.obj.x=-100;setTimeout(function(){a.respawn=!0},1E3);if(a.orbs.length)for(var b=0;b<a.orbs.length;b++)a.orbs[b].kill();
$("#ui-bottom > ul > li").removeClass().eq(0).addClass("active")};a.fire=function(){if(!a.active)return!1;if(a.lastBullet<(new Date).getTime()-150&&15>game.playerBulletsContainer.children.length){if(a.orbs.length)for(var b in a.orbs)a.orbs[b].fire();switch(a.special){case 1:case 2:b=new Bitmap(game.preloader.getResult("bullet-1").src);b.x=a.obj.x+a.obj.regX;b.y=a.obj.y-a.obj.regY;b.power=1;game.level.bullets.fired++;game.playerBulletsContainer.addChild(b);break;case 3:case 4:b=new Bitmap(game.preloader.getResult("bullet-1").src);
b.x=a.obj.x+a.obj.regX;b.y=a.obj.y-a.obj.regY+10;b.power=1;game.level.bullets.fired++;var c=new Bitmap(game.preloader.getResult("bullet-1").src);c.x=a.obj.x+a.obj.regX;c.y=a.obj.y-a.obj.regY-10;c.power=1;game.playerBulletsContainer.addChild(b);game.playerBulletsContainer.addChild(c);break;case 5:b=new Bitmap(game.preloader.getResult("bullet-1").src),b.x=a.obj.x+a.obj.regX+20,b.y=a.obj.y-a.obj.regY,b.power=1,game.level.bullets.fired++,c=new Bitmap(game.preloader.getResult("bullet-1").src),c.x=a.obj.x+
a.obj.regX+40,c.y=a.obj.y-a.obj.regY+35,c.power=1,c.rotation=-45,game.playerBulletsContainer.addChild(b),game.playerBulletsContainer.addChild(c)}a.lastBullet=(new Date).getTime()}};a.createOrb=function(){if(1==a.orbs.length)return!1;var b=new Bitmap(game.preloader.getResult("orb").src);b.scaleX=b.scaleY=1;b.kill=function(){a.orbs.splice(b,1);game.stage.removeChild(b)};b.fire=function(){var a=new Bitmap(game.preloader.getResult("orb-bullet").src);a.x=b.x;a.y=b.y;a.power=0.5;a.scaleX=a.scaleY=0.5;game.playerBulletsContainer.addChild(a)};
a.orbs.push(b);game.stage.addChild(b)};a.reset=function(){game.stage.removeChild(a.obj);if(a.orbs.length)for(var b in a.orbs)a.orbs[b].kill();a.init()};a.updateBullets=function(){for(var a in game.playerBulletsContainer.children){var c=game.playerBulletsContainer.children[a];c.x+=30;0!=c.rotation&&(c.y+=-30);game.playerBulletsContainer.children[a].x>game.canvas.width+50&&game.playerBulletsContainer.removeChild(game.playerBulletsContainer.children[a])}};a.powerup=function(){a.special++;if(0<a.special)switch(5<
a.special&&(a.special=5),a.special){case 2:a.createOrb()}$("#ui-bottom > ul > li").removeClass().eq(a.special-1).addClass("active")};a.tick=function(){a.respawn&&(a.obj.alpha=0==game.ticks%2?1:0,a.obj.x+=5,a.obj.y=240,100<=a.obj.x&&(a.obj.alpha=1,a.respawn=!1,a.active=!0));a.active&&(a.moveLeft?(a.obj.x-=10,0>=a.obj.x&&(a.obj.x=0)):a.moveRight&&(a.obj.x+=10,740<a.obj.x&&(a.obj.x=740)),a.moveUp?60<a.obj.y-10&&(a.obj.y-=10):a.moveDown&&420>a.obj.y+10&&(a.obj.y+=10),a.fireHeld&&a.fire());a.updateBullets();
if(a.orbs.length)for(var b in a.orbs){var c=a.orbs[b];c.offsetX=10*Math.cos(game.ticks/10)*b;c.offsetY=5*Math.sin(game.ticks/7);c.x=c.x+0.1*(a.obj.x-c.x)+c.offsetX;c.y=c.y+0.1*(a.obj.y-c.y)+c.offsetY}}};
var Powerup=function(b){var a=new Bitmap(game.preloader.getResult("power-1").src);a.x=b.x;a.y=b.y-10;a.regX=a.width/2;a.regY=a.height/2;game.powerupsContainer.addChild(a);a.tick=function(){if(game.powerupsContainer.children.length){var a=game.powerupsContainer.children[0];a.x-=2;-50>a.x&&game.powerupsContainer.removeChild(a)}}};
var Weapon=function(a){this.obj={};switch(a){case "SINGLELINEAR":return new SingleLinear;case "SINGLEDIRECTIONAL":return new SingleDirectional}};
var SingleDirectional=function(){this.obj=new Bitmap(game.preloader.getResult("enemy-bullet-2").src);this.interval=Utils.randRange(1.2,1.7);var a=this;this.direction=180;this.angle;this.obj.velocity={x:-20,y:0};this.shoot=function(b){this.interval-=0.03;0>=this.interval&&(a.direction=Math.atan2(game.player.obj.y-b.y,game.player.obj.x-b.x)*(180/Math.PI),game.enemyBulletsContainer.addChild(this.obj),a.obj.x=b.x,a.obj.y=b.y,a.angle=a.direction*Math.PI/180,a.obj.rotation=a.direction+Math.PI+180,a.obj.velocity=
{x:20*Math.cos(a.angle),y:20*Math.sin(a.angle)},this.interval=Utils.randRange(1.2,1.7))};this.obj.tick=function(){a.obj.x+=a.obj.velocity.x;a.obj.y+=a.obj.velocity.y;-150>a.obj.x&&game.enemyBulletsContainer.removeChild(a.obj)}};
var SingleLinear=function(){this.obj=new Bitmap(game.preloader.getResult("enemy-bullet").src);this.interval=Utils.randRange(1,1.5);var a=this;this.obj.velocity={x:-20,y:0};this.shoot=function(a,b,c){this.interval-=0.03;b||(b=a.x-a.regX);c||(c=a.y-a.regY);0>=this.interval&&(this.obj.x=b,this.obj.y=c,game.enemyBulletsContainer.addChild(this.obj),this.interval=Utils.randRange(1,1.5))};this.obj.tick=function(){a.obj.x+=a.obj.velocity.x;a.obj.y+=a.obj.velocity.y;0>a.obj.x&&game.enemyBulletsContainer.removeChild(a.obj)}};
